---
kind: Deployment
apiVersion: apps/v1
metadata:
   name: project-1
   namespace: default
   labels:
       app: project-1
spec:
   replicas: 1
   selector:
        matchlabels:
             app: project-1
   template:
       metadata:
         labels:
            app: project-1
       spec:
        containers:
         - name: project-1
           image: "joejoeb/project"
           ports:
               - containerport: 3000

---
apiVersion: v1
kind: Service
metadata:
    name: project-1
    namespace: default
spec:
   selector:
      app: project-1
   type: LoadBalancer
   ports:
       - name: http
         targetPort: 3000
         port: 80

